### ISSUE TITLE
Design sales page

### ISSUE THREAD

**Issue by hypesystem** [hypesystem/etree2#29]

**Comment by hypesystem** [comment]
I will post some screens of v0 (2014) when I get home

**Comment by Arth101** [comment]
![14407996_10210413594754616_1715631573_o](https://cloud.githubusercontent.com/assets/8166831/18753750/99a7264e-80e6-11e6-9def-8c4c642046a6.png)
![14423655_10210413594674614_261719441_o](https://cloud.githubusercontent.com/assets/8166831/18753755/99d56e1e-80e6-11e6-8819-0ff82b286572.png)
![14423693_10210413594954621_2043194427_o](https://cloud.githubusercontent.com/assets/8166831/18753751/99c11b12-80e6-11e6-8c83-6cfd3fd47dc1.png)
![14424190_10210413594714615_336760046_o](https://cloud.githubusercontent.com/assets/8166831/18753754/99d115c6-80e6-11e6-928b-4b4c89352328.png)
![14455938_10210413594514610_1583214851_o](https://cloud.githubusercontent.com/assets/8166831/18753752/99c920aa-80e6-11e6-9867-51b090ec807c.png)
![14456871_10210413594554611_191191581_o](https://cloud.githubusercontent.com/assets/8166831/18753753/99cabfdc-80e6-11e6-826a-a8269cea263d.png)

**Comment by hypesystem** [comment]
Change of plans: we need the "pick up locations" section anyway. We are going to find some partners like that :-)

**Comment by hypesystem** [comment]
![etree sizes guess](https://cloud.githubusercontent.com/assets/859106/18816301/b06656c2-8346-11e6-95a4-b7f6f1e95a48.png)

Tror størrelserne kommer til at være disse

**Comment by hypesystem** [comment]
http://jule3et.dk/ er en konkurrent med stort set præcis samme model som os. Vi er billigere, dw. De har en liste over postnumre de leverer til på deres forside. Lad os tage udgangspunkt i den :smile:

**Comment by hypesystem** [comment]
See sales page at http://etree.dk/?forceState=salesStarted

**Comment by Arth101** [comment]
- skal du have fod på træet? (+50)
- skal vi hente træet efter jul? (+200)

**Comment by Arth101** [comment]
related pr: https://github.com/hypesystem/etree2/pull/47
