### ISSUE TITLE
Email template

### ISSUE THREAD

**Issue by hypesystem** [hypesystem/etree2#32]
low prio rn

**Comment by Arth101** [comment]
What do we want to do with the email? Is it a newsletter, or a order confirmation, or something else?

**Comment by hypesystem** [comment]
- "Invite your friends to get them 15% off delivery" newsletter
- "The sale has started" newsletter
- Order confirmation (invoice pdf attached)
- "What did you think of etree this year" newsletter

**Comment by hypesystem** [comment]
Notice: nobody is assigned to this yet, it is here so we remember it.

**Comment by hypesystem** [comment]
Done
