### ISSUE TITLE
Automatically send off emails

### ISSUE THREAD

**Issue by hypesystem** [hypesystem/etree2#36]
We need a way to programatically schedule emails. For example, every year on the 20/10 an email should go to the people on the prelaunch list and tell them to invite their friends. We need to ensure that exactly 1 email is sent.

There are some other email cases, too. I will detail all of them pretty soon.

**Comment by ath88** [comment]
https://github.com/ath88/email-service

You should fork this. :)

**Comment by hypesystem** [comment]
Nice!

**Comment by hypesystem** [comment]
@ath88 will be doing some final extraction, making it possible to trigger emails from the main etree project. After that, this is concluded.

Re: forking, we will wait until we create an etree organization on github (after company registrations, etc, etc, will happen at some point i promise).

**Comment by hypesystem** [comment]
This done
