### ISSUE TITLE
Duplicate text

### ISSUE THREAD

**Issue by ath88** [hypesystem/etree2#69]
Det ser lidt sært ud med ordene "Leveres til døren" gentaget så mange gange. Hvad tænker I?

![image](https://cloud.githubusercontent.com/assets/167812/19887145/12f9bdc2-a027-11e6-8dbf-c1b52018631e.png)

**Comment by hypesystem** [comment]
Hey, så er man da ikke i tvivl!

**Comment by ath88** [comment]
Sandt. :) 

Min moder forklarede blot at hun blev forvirret først, da hun ikke umiddelbart forbandt størrelsen til prisen under.

**Comment by hypesystem** [comment]
God pointe. Lidt samme visuelle problem som i #70 tror jeg :smile:

**Comment by ath88** [comment]
Det er meget muligt.
